package jzero.admin.model.ge;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

import jzero.admin.model.AsCommonSetting;
import jzero.admin.security.model.User;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("as_common_setting", AsCommonSetting.class);
 	}
}

