package jzero.admin.security.model;

import java.util.List;

import jzero.admin.model.base.BaseSecRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleMenu extends BaseSecRoleMenu<RoleMenu> {
	public static final RoleMenu dao = new RoleMenu();

	public List<RoleMenu> findMyMenuId(int roldId) {
		String sql = "select menu_id from sec_role_menu where role_id=?";
		return find(sql,roldId);
	}
}
