package jzero.admin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAsFriendshipLink<M extends BaseAsFriendshipLink<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setIsshow(java.lang.Boolean isshow) {
		set("isshow", isshow);
		return (M)this;
	}
	
	public java.lang.Boolean getIsshow() {
		return get("isshow");
	}

	public M setOrderby(java.lang.Integer orderby) {
		set("orderby", orderby);
		return (M)this;
	}
	
	public java.lang.Integer getOrderby() {
		return getInt("orderby");
	}

}
