package jzero.admin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAsCommonSetting<M extends BaseAsCommonSetting<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setValue(java.lang.String value) {
		set("value", value);
		return (M)this;
	}
	
	public java.lang.String getValue() {
		return getStr("value");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setNotes(java.lang.String notes) {
		set("notes", notes);
		return (M)this;
	}
	
	public java.lang.String getNotes() {
		return getStr("notes");
	}

	public M setIssystem(java.lang.Boolean issystem) {
		set("issystem", issystem);
		return (M)this;
	}
	
	public java.lang.Boolean getIssystem() {
		return get("issystem");
	}

}
