package jzero.admin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAsDbBackup<M extends BaseAsDbBackup<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDbname(java.lang.String dbname) {
		set("dbname", dbname);
		return (M)this;
	}
	
	public java.lang.String getDbname() {
		return getStr("dbname");
	}

	public M setSwitch(java.lang.Integer _switch) {
		set("switch", _switch);
		return (M)this;
	}
	
	public java.lang.Integer getSwitch() {
		return getInt("switch");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setCycleDay(java.lang.Integer cycleDay) {
		set("cycleDay", cycleDay);
		return (M)this;
	}
	
	public java.lang.Integer getCycleDay() {
		return getInt("cycleDay");
	}

}
