package jzero.admin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAsFrontNav<M extends BaseAsFrontNav<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setUpid(java.lang.Integer upid) {
		set("upid", upid);
		return (M)this;
	}
	
	public java.lang.Integer getUpid() {
		return getInt("upid");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setBlank(java.lang.Boolean blank) {
		set("blank", blank);
		return (M)this;
	}
	
	public java.lang.Boolean getBlank() {
		return get("blank");
	}

	public M setDateline(java.util.Date dateline) {
		set("dateline", dateline);
		return (M)this;
	}
	
	public java.util.Date getDateline() {
		return get("dateline");
	}

	public M setIsClosed(java.lang.Boolean isClosed) {
		set("isClosed", isClosed);
		return (M)this;
	}
	
	public java.lang.Boolean getIsClosed() {
		return get("isClosed");
	}

	public M setColor(java.lang.String color) {
		set("color", color);
		return (M)this;
	}
	
	public java.lang.String getColor() {
		return getStr("color");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public M setOrders(java.lang.Integer orders) {
		set("orders", orders);
		return (M)this;
	}
	
	public java.lang.Integer getOrders() {
		return getInt("orders");
	}

}
