package jzero.admin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAsNotesModel<M extends BaseAsNotesModel<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setSignature(java.lang.String signature) {
		set("signature", signature);
		return (M)this;
	}
	
	public java.lang.String getSignature() {
		return getStr("signature");
	}

	public M setModelid(java.lang.String modelid) {
		set("modelid", modelid);
		return (M)this;
	}
	
	public java.lang.String getModelid() {
		return getStr("modelid");
	}

	public M setIssystem(java.lang.Boolean issystem) {
		set("issystem", issystem);
		return (M)this;
	}
	
	public java.lang.Boolean getIssystem() {
		return get("issystem");
	}

	public M setSystemtype(java.lang.Integer systemtype) {
		set("systemtype", systemtype);
		return (M)this;
	}
	
	public java.lang.Integer getSystemtype() {
		return getInt("systemtype");
	}

}
