package jzero.admin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAsBackupRecord<M extends BaseAsBackupRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDateLine(java.util.Date dateLine) {
		set("dateLine", dateLine);
		return (M)this;
	}
	
	public java.util.Date getDateLine() {
		return get("dateLine");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setIndex(java.lang.Integer index) {
		set("index", index);
		return (M)this;
	}
	
	public java.lang.Integer getIndex() {
		return getInt("index");
	}

	public M setDataname(java.lang.String dataname) {
		set("dataname", dataname);
		return (M)this;
	}
	
	public java.lang.String getDataname() {
		return getStr("dataname");
	}

}
