package jzero.admin.model;

import java.util.Map;

import org.apache.commons.lang.StringUtils;

import com.jfinal.plugin.activerecord.Page;

import jzero.admin.model.base.BaseAsCommonSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AsCommonSetting extends BaseAsCommonSetting<AsCommonSetting> {
	public static final AsCommonSetting dao = new AsCommonSetting().dao();

	// 获取model的基本字段信息
	public Map<String, Object> getColumns() {
		return _getAttrs();
	}

	/**
	 * 
	 * @category 根据键查询值
	 * @author MC
	 * @date 2018年7月30日 下午1:59:01
	 * @param skey
	 * @return
	 */
	public AsCommonSetting findByKey(String skey) {
		String sql = "select * from as_common_setting where name = ?";
		if (findFirst(sql, skey) == null) {
			AsCommonSetting setting = new AsCommonSetting();
			setting.set("name", skey);
			setting.set("value", "");
			setting.save();
			return setting;
		} else {
			return findFirst(sql, skey);
		}
	}

	/**
	 * 
	 * @category 根据name值获取对应value
	 * @author MC
	 * @date 2018年7月30日 下午1:58:33
	 * @param key
	 * @return
	 */
	public String getValue(String key) {
		String sql = "select * from as_common_setting where name=?";
		AsCommonSetting commonSetting = findFirst(sql, key);
		if (commonSetting == null)
			return null;
		return commonSetting.getValue().trim();
	}

	/**
	 * 
	 * @category 获取基础设置list
	 * @author MC
	 * @date 2018年7月30日 下午2:37:20
	 * @param pageNumber
	 * @param pageSize
	 * @param name
	 * @return
	 */
	public Page<AsCommonSetting> paginate(int pageNumber, int pageSize, String name) {
		String sql = " from as_common_setting  where type = 0";
		if (StringUtils.isNotEmpty(name)) {
			sql += " and name like '%" + name + "%' ";
		}
		return paginate(pageNumber, pageSize, "select * ", sql);
	}
}
