package jzero.admin.model;

import java.sql.Time;

import com.jfinal.plugin.activerecord.Db;

import jzero.admin.model.base.BaseAsDbBackup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AsDbBackup extends BaseAsDbBackup<AsDbBackup> {
	public static final AsDbBackup dao = new AsDbBackup().dao();

	/**
	 * 获取数据库大小
	 * 
	 * @author lpy
	 * @Date 2019年1月25日 下午6:30:59
	 */
	public String getDbSize(String dbName) {
		String sql = "select concat(round(sum(data_length/1024/1024),2),'MB') as data from tables where table_schema='"
				+ dbName + "'";
		return Db.use("mysql_information").findFirst(sql).getStr("data");
	}

	/**
	 * 获取数据库自动备份配置的状态
	 * 
	 * @author lpy
	 * @Date 2019年1月25日 下午6:32:21
	 */
	public AsDbBackup getDbAutoBackupStatus(String dbName) {
		String sql = "select * from as_db_backup where dbname = '" + dbName + "'";
		return AsDbBackup.dao.findFirst(sql);
	}

	/**
	 * 创建数据库自动备份导出任务
	 * 
	 * @author lpy
	 * @Date 2019年1月25日 下午6:38:27
	 */
	public int setDbAutoBackupTask(Time time, String cycleDay, String dbName) {
		String sql = "update as_db_backup set switch = 1";
		sql += ", time = '" + time + "'";
		sql += ", cycleDay = " + cycleDay;
		sql += " where dbname = '" + dbName + "'";
		return Db.update(sql);
	}

	/**
	 * 关闭数据库自动备份导出任务
	 * 
	 * @author lpy
	 * @Date 2019年1月25日 下午6:38:53
	 */
	public int closeAutoBackupTask(String dbName) {
		String sql = "update as_db_backup set switch = 0 where dbname = 'xc_lab_erp'";
		return Db.update(sql);
	}
}
