package jzero.admin.model;
import java.util.List;

import com.jfinal.plugin.activerecord.Page;

import jzero.admin.model.base.BaseAsFriendshipLink;
/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AsFriendshipLink extends BaseAsFriendshipLink<AsFriendshipLink> {
	public static final AsFriendshipLink dao = new AsFriendshipLink();

	public Page<AsFriendshipLink> paginate(int pageNumber, int pageSize) {
		String select = "select * ";
		String sql = "from as_friendship_link";
		return paginate(pageNumber, pageSize, select, sql);
	}
	public List<AsFriendshipLink> findShowLink() {
		String select = "select * ";
		String sql = "from as_friendship_link where isshow = 1";
		return find(select+sql);
	}
}