package jzero.admin.model;

import com.jfinal.plugin.activerecord.Page;

import jzero.admin.common.utils.EduStringUtil;
import jzero.admin.model.base.BaseAsLogPhone;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AsLogPhone extends BaseAsLogPhone<AsLogPhone> {
	public static final AsLogPhone dao = new AsLogPhone().dao();
	/**
	 * 
	 * @category 获取短信历史记录
	 * @author MC
	 * @return 
	 * @date 2018年8月3日 下午4:15:33
	 * @return
	 */
	public Page<AsLogPhone> findHistoryRecord(int pageNumber, int pageSize,String tel, int apiType, int status) {
		String sql = " from as_log_phone where 1=1";
		if (!EduStringUtil.isEmpty(tel)) {
			sql += " and tel like '%"+tel+"%'";
		}
		if (apiType!=-1) {
			sql += " and apiType = "+ apiType;
		}
		if (status!=-1) {
			sql += " and status = "+status;
		}
		return paginate(pageNumber, pageSize, "select * ", sql);
	}
}
