package jzero.admin.model;

import jzero.admin.model.base.BaseAsLogEmail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AsLogEmail extends BaseAsLogEmail<AsLogEmail> {
	public static final AsLogEmail dao = new AsLogEmail().dao();
}
