package jzero.admin.model;

import jzero.admin.model.base.BaseAsNotesSendHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AsNotesSendHistory extends BaseAsNotesSendHistory<AsNotesSendHistory> {
	
}
