package jzero.admin.model;

import jzero.admin.model.base.BaseAsPhoneCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AsPhoneCode extends BaseAsPhoneCode<AsPhoneCode> {
	
}
