package jzero.admin.model;

import java.util.List;

import com.alibaba.druid.util.StringUtils;
import com.jfinal.plugin.activerecord.Page;

import jzero.admin.model.base.BaseAsRestoreRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AsRestoreRecord extends BaseAsRestoreRecord<AsRestoreRecord> {
	public static final AsRestoreRecord dao = new AsRestoreRecord();

	public Page<AsRestoreRecord> paginate(int pageNumber, int pageSize,String dateLine) {
		String select = "select ar.*,su.realname,ab.url";
		String sql = "from as_restore_record as ar inner join sec_user as su on su.id =ar.uid inner join as_backup_record as ab on ab.id = ar.bid";
		if (!StringUtils.isEmpty(dateLine)) {
			sql+=(" where dateLine between '"+dateLine+" 00:00:00' and '"+dateLine+" 23:59:59'");
		}
		return paginate(pageNumber, pageSize, select, sql);
	}
	public List<AsRestoreRecord> findAll() {
		String select = "select * ";
		String sql = "from as_restore_record";
		return find(select+sql);
	}
}
