package jzero.admin.model;

import jzero.admin.model.base.BaseAsSheduleLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AsSheduleLog extends BaseAsSheduleLog<AsSheduleLog> {
	
}
